contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bsrqc channel"
    url: https://nfcore.slack.com/channels/bsrqc
    about: Discussion about the nf-core/bsrqc pipeline
